== Write a test - Testatoo functionalites
'''
==== Select a component with $ function

The $ function is the access point for fetching component on the page. The $ function accepts a CSS3 selector to target your component.

The signature of the $ function is the following…

[source, java]
-------------------------------------------------------------------------------
$('css selector')

// Samples
$('#myId')                 <1>
$('.myClass')              <2>
$('ul li:first-child')     <3>
$('[data-role=button]')    <4>
-------------------------------------------------------------------------------

<1> Match the DOM element on the page with id "myId"
<2> Match all DOM elements on the page with the css class "myClass"
<2> Match all DOM elements on the page that are the first child of an unordered list
<4> Match all DOM elements on the page that have attribute "data-role" equals to "button"

Our experience demonstrated that *we never need complex selector.* If you write tests first, we use the semantic
carried by the tested component. In the code, this is reflected by a custom tag, the sequence in the page, a role
attribute, or an id.

//TODO : examples (custom tag : with Angular Directive or Web Components)

[IMPORTANT]
====
Once the component is selected, it *MUST BE TYPED* through the *"as"* keyword.

[source, java]
-------------------------------------------------------------------------------
TextField textField = $('#text_field') as TextField
Button button = $('#button') as Button
-------------------------------------------------------------------------------
====

In Testatoo you never select an anonymous DOM element. Every DOM element must be the representation of a UI concept.
But wait a moment: How can you know if a button is a button!? Indeed, in HTML, a Button can be represented in many ways:

[source, html]
-------------------------------------------------------------------------------
<button id="button">My Button</button>
<input id="button" type="button" value="My Button">
<input id="button" type="submit" value="My Button">

-------------------------------------------------------------------------------

This is the magic of Testatoo. We will see later how it works and how to override this behavior and easily add new component types.

[IMPORTANT]
====
The $ function *NEEDS* to target a *UNIQUE* component. If you want to work with a list of components you need to use the $$ function.

The following code fails with the message *"Component defined by jQuery expression $('#mySelect option') is not unique: got x"*
[source, java]
-------------------------------------------------------------------------------
Item item = $('#mySelect option') as Item;
item.should { be visible }
-------------------------------------------------------------------------------
because through the selector expression, we try to target a list of items (options) of a select to evaluate their visibility.
====

==== Multi selection with $$ function

The "$$" function allows you to make assertion on a list of elements. The $$ function accepts a CSS3 selector to target a list of components.

[source, java]
-------------------------------------------------------------------------------
Components<TextField> textFields = $$('[type="text"]') of TextField     // Find all TextFields in the page

textFields.each {           // Iterates on TextFields
    it.should {
        be enabled
        be visible
        be empty
    }
}

textFields.each { it ->
    fill it with 'TESTATOO!' // Enter 'TESTATOO' on all TextFields
}

textFields.each {
    it.should {
        be filled
        have text('My Value!')
    }
}
-------------------------------------------------------------------------------

==== Navigate with find function

Once a component is selected you can easily navigate through its children with the find method attached to the component:
[source, java]
-------------------------------------------------------------------------------
Form form = $('form:first') as Form;
Button save_button = form.find('button:last') as Button
-------------------------------------------------------------------------------

=== Evaluate a component

On each component we can evaluate associated *Properties* and *States*.
Each evaluation can be operated in two ways:

* The direct way with the *is(...)* method for State and the *has(...)* method for Property
* The differed way with the *should()* method


[source, java]
-------------------------------------------------------------------------------
// Direct usage

button.is(enabled)          // State
button.has(text) == 'Ok'    // Property

// Differed usage
button.should {
    be enabled              // State
    have text('Ok')         // Property
}

-------------------------------------------------------------------------------


The differed way MUST be preferred. This approach includes an inner waitUntil. So if a condition in the should is not reached,
the evaluation is evaluated again every 200ms until 2 seconds.

[NOTE]
====
You can change the wait until duration in Testatoo.

[source, java]
-------------------------------------------------------------------------------
Testatoo.waitUntil = 2.seconds
-------------------------------------------------------------------------------
====


==== Properties

==== States


=== Interact with components

==== Low level actions

Testatoo allows the specifier to interact with the application through the usage of default inputs like Keyboard, Mouse or Fingers.

===== Mouse interactions

The mouse events supported are :

*click_on*, +
*double_click_on*, +
*right_click_on*, +
*hovering_mouse_on*, +
*drag ... on ...*

[source, java]
-------------------------------------------------------------------------------
Button button = $('#button') as Button
Panel panel_1 = $('#Panel_1) as Panel
Panel panel_2 = $('#Panel_2) as Panel

click_on button
double_click_on button
right_click_on button
hovering_mouse_on panel_1
drag panel_1 on panel_2
-------------------------------------------------------------------------------

===== Keyboard interactions

For the keyboard events we have done a nice work to make this easy:
Only ONE Method to represent them all: *the type(...) method*

[source, java]
-------------------------------------------------------------------------------
TextField textField = $('#textfield') as TextField

click_on textField
type('testatoo')
-------------------------------------------------------------------------------

If you need the usage of a simple key modifier....

[source, java]
-------------------------------------------------------------------------------
TextField textField = $('#textfield') as TextField

click_on textField
type(SHIFT + 'testatoo') // => TESTATOO
-------------------------------------------------------------------------------

Or a complex one....

[source, java]
-------------------------------------------------------------------------------
TextField textField = $('#textfield') as TextField

click_on textField
type(CTRL + ALT + SHIFT + 'x')
-------------------------------------------------------------------------------


===== Touch events
Testatoo does not support touch event for the moment.

==== High level actions

Testatoo allows the specifier to interact with the UI domain with a more semantic language.

===== Fill / Clear field

===== Check / Uncheck radio and checkbox

===== Select / Unselect item

===== Submit / Reset form